# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RadioMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonNext = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNext.setGeometry(QtCore.QRect(460, 190, 80, 51))
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.pushButtonPause = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPause.setGeometry(QtCore.QRect(360, 220, 80, 71))
        self.pushButtonPause.setObjectName("pushButtonPause")
        self.VolumeSlider = QtWidgets.QSlider(self.centralwidget)
        self.VolumeSlider.setGeometry(QtCore.QRect(730, 160, 20, 181))
        self.VolumeSlider.setOrientation(QtCore.Qt.Vertical)
        self.VolumeSlider.setInvertedAppearance(False)
        self.VolumeSlider.setInvertedControls(False)
        self.VolumeSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.VolumeSlider.setTickInterval(10)
        self.VolumeSlider.setObjectName("VolumeSlider")
        self.pushButtonMute = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMute.setGeometry(QtCore.QRect(630, 260, 80, 23))
        self.pushButtonMute.setObjectName("pushButtonMute")
        self.TextBoxStation = QtWidgets.QListView(self.centralwidget)
        self.TextBoxStation.setGeometry(QtCore.QRect(30, 120, 239, 411))
        self.TextBoxStation.setObjectName("TextBoxStation")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 360, 111, 16))
        self.label.setObjectName("label")
        self.textCurrentSong = QtWidgets.QLineEdit(self.centralwidget)
        self.textCurrentSong.setGeometry(QtCore.QRect(30, 50, 751, 23))
        self.textCurrentSong.setReadOnly(True)
        self.textCurrentSong.setObjectName("textCurrentSong")
        self.pushButtonPlay = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPlay.setGeometry(QtCore.QRect(360, 130, 80, 81))
        self.pushButtonPlay.setObjectName("pushButtonPlay")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 111, 16))
        self.label_2.setObjectName("label_2")
        self.pushButtonPrev = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPrev.setGeometry(QtCore.QRect(270, 190, 80, 51))
        self.pushButtonPrev.setObjectName("pushButtonPrev")
        self.TextBoxStatus = QtWidgets.QTextEdit(self.centralwidget)
        self.TextBoxStatus.setGeometry(QtCore.QRect(290, 390, 231, 141))
        self.TextBoxStatus.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.TextBoxStatus.setReadOnly(True)
        self.TextBoxStatus.setOverwriteMode(False)
        self.TextBoxStatus.setObjectName("TextBoxStatus")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(520, 340, 256, 192))
        self.textBrowser.setAutoFormatting(QtWidgets.QTextEdit.AutoBulletList)
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menuBar.setObjectName("menuBar")
        self.menuDatei = QtWidgets.QMenu(self.menuBar)
        self.menuDatei.setObjectName("menuDatei")
        MainWindow.setMenuBar(self.menuBar)
        self.action_ffnen = QtWidgets.QAction(MainWindow)
        self.action_ffnen.setObjectName("action_ffnen")
        self.action_ffnen_2 = QtWidgets.QAction(MainWindow)
        self.action_ffnen_2.setObjectName("action_ffnen_2")
        self.menuDatei.addAction(self.action_ffnen_2)
        self.menuBar.addAction(self.menuDatei.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MY RADIO PLAYER"))
        self.pushButtonNext.setText(_translate("MainWindow", "Next"))
        self.pushButtonPause.setText(_translate("MainWindow", "Pause"))
        self.pushButtonMute.setText(_translate("MainWindow", "Mute"))
        self.label.setText(_translate("MainWindow", "Status Message"))
        self.pushButtonPlay.setText(_translate("MainWindow", "Play"))
        self.label_2.setText(_translate("MainWindow", "Radio Station"))
        self.pushButtonPrev.setText(_translate("MainWindow", "Prev"))
        self.menuDatei.setTitle(_translate("MainWindow", "Datei"))
        self.action_ffnen.setText(_translate("MainWindow", "Öffnen"))
        self.action_ffnen_2.setText(_translate("MainWindow", "Öffnen"))

